### ISSUE TITLE
misc changes

### ISSUE THREAD

**Issue by s4t13** [nobe4/dotfiles#3]
`brew install --cask rectangle`

**Comment by s4t13** [comment]
In vimrc, L194
```
set spellcapcheck=
```

**Comment by s4t13** [comment]
```ifconfig -v | grep "VPN:" | sed -E 's/[^"]+"VPN: ([^"]+)"/\1/'```

**Comment by nobe4** [comment]
`ffmpeg -loop 1 -f image2 -i A.jpg -i A.mp3 -vf 'crop=in_w:in_w*9/16,scale=1920:1080,fps=fps=60' -pix_fmt yuv420p -vcodec libx264 -shortest -strict -2 A.mp4`

**Comment by nobe4** [comment]
https://til.hashrocket.com/posts/ebvekqrzvx-change-tmux-working-directory-while-in-session

Change tmux working directory while in session
If you’d like the working directory of tmux to change while you are working in that tmux session, you can use the attach_session command at the tmux command promt.

To get to the tmux command prompt use <leader>: and then use attach-session with the -c flag.

# at the tmux command prompt
:attach-session -t . -c new_working_dir

**Comment by nobe4** [comment]
```vim
nnoremap Y y$        " (see :h Y)

" Keep search centered
nnoremap n nzz
nnoremap N Nzz


```

**Comment by nobe4** [comment]
All done
